recipe: default.v1
assistant_id: 20260405-132452-windy-diatonic
language: en

pipeline:
  - name: CompactLLMCommandGenerator
    llm:
      model_group: gemini_llm
    flow_retrieval:
      embeddings:
        model_group: huggingface_llm

policies:
  - name: FlowPolicy
  - name: IntentlessPolicy
    llm:
      model_group: gemini_llm
    embeddings:
      model_group: huggingface_llm